### ISSUE TITLE
Errors in exist.log when opening app

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/function-documentation#19] opened 2018-02-14 18:34 UTC
exist.log reports many lines of:
```
2018-02-14 18:50:50,030 [qtp1616515493-80] ERROR (FunError.java [eval]:139) - Not found: (http://exist-db.org/apps/site-utils#NOT_FOUND):Not found 
```

exist `4.0.0`
fundocs `0.9`
java `8`
macOS `10.13.3`

**Comment by joewiz** [comment] 2018-02-15 00:53
I can confirm each request to http://localhost:8080/exist/apps/fundocs/index.html adds 17 instances of this error. This issue is actually caused by the app's `templates/page.html` template's calls to `site:expand-links`, which tries to dynamically expand all of that page's links to other apps. References to missing apps like `{demo}` trigger the error at https://github.com/eXist-db/shared-resources/blob/master/content/siteutils.xql#L65. Installing the demo apps—which used to be included in the installer until https://github.com/eXist-db/exist/commit/36c20a9b1ac33d14001d05073f3e39560021d36c#diff-07d50b8b644e3c6983d976908f880efd—reduces the number of errors to 4. I haven't tracked down these remaining culprits but wanted to report these findings for now.

**Comment by joewiz** [comment] 2018-02-15 04:59
The remaining 4 errors are due to a mismatch between the `{doc}` shorthand reference and the documentation app's expath-pkg.xml `@abbrev` value: `exist-documentation`. The function that performs the lookup of these abbreviations, [`apputil:resolve-abbrev()`](https://github.com/eXist-db/shared-resources/blob/master/content/apputil.xql#L47-L62), relies on this value from expath-pkg.xml's `package/@abbrev`. 

Generally, an app's `@abbrev` should correspond to the name of the target collection into which it is installed. Since `exist-documentation` is used nowhere else—either in the app's target collection name or in the repository—I would favor changing its `@abbrev` to "doc". 

(I actually prefer the app's original name, "docs," which was changed to "doc" only to accommodate the development of Loren Cahlander's replacement for the original app.)

Also, since we have a graceful 404 functionality that advises people who click on links to install the missing apps via Dashboard, perhaps the error here should be demoted to a warning.

**Comment by joewiz** [comment] 2018-02-15 05:03
But these 17 errors actually are unrelated to the subject of this issue. Would you prefer to rename this issue to be about the errors in exist.log, or would you prefer to close this as a dupe of #11?

**Comment by adamretter** [comment] 2018-02-16 12:44
It seems the function documentation was never updated, i.e. it does not use `exist-apps-parent` I will send a PR.

**Closed** 2024-12-30 14:27 UTC
